### ISSUE TITLE
Any plans to submit this to the official `nvim-treesitter` repo?

### ISSUE THREAD

**Issue by musjj** [vantreeseba/tree-sitter-haxe#10]
https://github.com/nvim-treesitter/nvim-treesitter
Would be nice to have this in the official repository, as it makes the installation process easier for neovim users.

**Comment by vantreeseba** [comment]
I will look into this.
I need to look over thus again for ensuring base functionality is complete enough for people pulling it in and expecting it to work :P

Good idea though, and I agree!

**Comment by vantreeseba** [comment]
I've started this, so closing this issue for now.
