### ISSUE TITLE
Adding support for interfaces

### ISSUE THREAD

**Issue by johhnry** [vantreeseba/tree-sitter-haxe#17]
Hi,

Thanks for making this!

Would it be possible to add support for interfaces? Currently it does this:

![image](https://github.com/vantreeseba/tree-sitter-haxe/assets/35373357/1508e4a2-13ca-41bf-84ed-8569e122c9bc)

**Comment by vantreeseba** [comment]
Dunno how I missed that, unless interfaces are newer lol.

Will do.

**Comment by johhnry** [comment]
Thanks it was quick!
