### ISSUE TITLE
String interpolation

### ISSUE THREAD

**Issue by kLabz** [vantreeseba/tree-sitter-haxe#3]
Add support for string interpolation:

```haxe
// Only for single quote strings 
var s = 'some string $someIdent and also ${someCode}';

// ${} goes back to haxe code, which can contain pretty much any expression
var s = 'which can be ${someCode.function() ? null : anyHaxeCode.here} too, which seems to fail on GH syntax highlighting too xD';
```

**Comment by vantreeseba** [comment]
![image](https://user-images.githubusercontent.com/316782/121959482-7d556100-cd2a-11eb-8c7c-6600da9abda8.png)

This seems mostly working for me, added some tests and etc.

**Comment by johhnry** [comment]
@kLabz @vantreeseba 

I'm sorry to dig up this old issue but it seems that it doesn't work for me:

![image](https://github.com/vantreeseba/tree-sitter-haxe/assets/35373357/af41ef02-9ef8-431f-a5dc-03e8e9b98e9d)

can someone confirm it?
