### ISSUE TITLE
using .code in switch expressions breaks highlighting

### ISSUE THREAD

**Issue by belowdecent** [vantreeseba/tree-sitter-haxe#32]
Seems similar to the #23
Using `[CHARACTER].code` inside switch expressions breaks highlighting
Minimal example I came up with
```
class TSBug {
	public static function main() {
		var ch = "b".code;
		switch (ch) {
			case "b".code:
				trace("bug");
			case "s".code:
				trace("bug");
			case "x".code:
				trace("bug");
		}
	}
}
```
![image](https://github.com/vantreeseba/tree-sitter-haxe/assets/28831846/05373ed2-4e80-49af-8ea2-70b36cef64c8)

Removing .code makes highlighting work again
![image](https://github.com/vantreeseba/tree-sitter-haxe/assets/28831846/8e7ceab6-fef5-4fbe-b7a8-4f909728434f)

**Comment by vantreeseba** [comment]
This should be fixed with v0.9.0
