### ISSUE TITLE
`tree-sitter generate` fails with "error: repetition quantifier expects a valid decimal"

### ISSUE THREAD

**Issue by miriti** [vantreeseba/tree-sitter-haxe#37]
Hi!

Maybe I'm doing something wrong here. Just cloned the latest version of `tree-sitter-haxe` (93c3ce595e41727670f7c0e6c88afe16b5384f0d). `cd` into the cloned directory and ran `tree-sitter generate` (`tree-sitter` version 0.22.2). It fails with this output:

```
Error processing rule escape_sequence

Caused by:
    regex parse error:
        u{[0-9a-fA-F]+}
          ^
    error: repetition quantifier expects a valid decimal
```

**Comment by vantreeseba** [comment]
Thanks for issue, I'll look into it.

**Comment by vantreeseba** [comment]
@miriti This should be fixed, there was an issue with the newest version of tree-sitter I guess, was something to do with some special char checking in regex, but seems to be good now.

**Comment by miriti** [comment]
Awesome! Thanks for fixing it! It works perfectly for me now.
